version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 891377367684.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t hangman-app .
      - echo Tagging the Docker image...
      - docker tag hangman-app:latest 891377367684.dkr.ecr.ap-south-1.amazonaws.com/hangman-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 891377367684.dkr.ecr.ap-south-1.amazonaws.com/hangman-app:latest
      - echo Build and push complete.
artifacts:
  files:
    - '**/*'

